name: Lint code

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths: ['**.js', '**.ts', '**.tsx', '**.json', '**.mjs', '**.cjs', 'config/.editorconfig', '.watchmanconfig', '.imgbotconfig']

concurrency:
  group: "${{ github.ref }}-lint"
  cancel-in-progress: true

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Lint JavaScript and Typescript with ESLint
        run: npm run lint
        env:
          CI: true

      - name: Install Prettier
        run: npm install prettier --save-dev
