name: Lint code

on:
  push:
    branches-ignore: [staging, production]
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.json'
      - '**.mjs'
      - '**.cjs'
      - 'config/.editorconfig'
      - '.watchmanconfig'
      - '.imgbotconfig'
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.json'
      - '**.mjs'
      - '**.cjs'
      - 'config/.editorconfig'
      - '.watchmanconfig'
      - '.imgbotconfig'

concurrency:
  group: "${{ github.ref }}-lint"
  cancel-in-progress: true

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Lint JavaScript and Typescript with ESLint
        run: npm run lint
        env:
          CI: true

      - name: Verify there's no Prettier diff
        run: |
          npm run prettier -- --loglevel silent
          if ! git diff --name-only --exit-code; then
            # shellcheck disable=SC2016
            echo 'Error: Prettier diff detected! Please run `npm run prettier` and commit the changes.'
            exit 1
          fi
